services:

  app-bot-commitia:
    build:
      context: ./bot
    ports:
      - "6013:6013"
    env_file:
      - .env
    restart: always
    networks:
      - project_network


networks:
  project_network:
    external: true
